services:
    web:
      build: ./django
      # command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
            - ./django/:/usr/src/app/
      # expose:
      #       - 8000
      ports:
            - 8000:8000
      env_file:
            - ./.env.dev
      depends_on:
            - db
    db:
      image: postgres:13.0-alpine
      volumes:
            - postgres_data:/var/lib/postgresql/data/
      environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev

#     nginx:
#       build: ./nginx
#       ports:
#             - 1337:80
#       depends_on:
#             - web

volumes:
  postgres_data: