services:
    web:
      build:
            context: ./django
            dockerfile: Dockerfile.prod

      command: gunicorn project.wsgi:application --bind 0.0.0.0:8000

      expose:
            - 8000
      volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media      
      env_file:
            - ./.env.prod
      depends_on:
            - db
    db:
      image: postgres:13.0-alpine
      volumes:
            - postgres_data:/var/lib/postgresql/data/
      environment:
            - ./.env.db
    nginx:
      build:  ./nginx
      volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
      ports:
            - 1337:80
      depends_on:
            - web        
volumes:
  postgres_data:
  static_volume:
  media_volume:  